version: 0.2

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - apt-get update && apt-get install -y docker.io
      - echo "Enabling Docker BuildKit..."
      - export DOCKER_BUILDKIT=1
      - echo "Fetching Docker Hub credentials from Secrets Manager..."
      - SECRET=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhublogin-4vcmMW --query SecretString --output text)
      - echo $SECRET | jq -r '.username' > /tmp/dockerhub_username
      - echo $SECRET | jq -r '.password' > /tmp/dockerhub_password
      - echo "Logging in to Docker Hub..."
      - docker login -u $(cat /tmp/dockerhub_username) -p $(cat /tmp/dockerhub_password)

  pre_build:
    commands:
      - echo "Listing files in the game directory..."
      - ls -l game/
      - echo "Building Docker image for game..."
      - cd game
      - docker build -t $DOCKERHUB_USERNAME/python-game:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - cd ..
      
  build:
    commands:
      - echo "Pushing Docker images to Docker Hub..."
      - docker push $DOCKERHUB_USERNAME/python-game:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $DOCKERHUB_USERNAME/python-webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
