version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhub-G8QpL5:username
    DOCKERHUB_PASSWORD: arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhub-G8QpL5:password

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - apt-get update && apt-get install -y docker.io
      - docker run --privileged --rm tonistiigi/binfmt --install all
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Building Docker image for game..."
      - cd game
      - docker buildx create --use
      - docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/python-game:$CODEBUILD_RESOLVED_SOURCE_VERSION --push .
      - cd ../webapp
      - echo "Building Docker image for webapp..."
      - docker buildx create --use
      - docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKERHUB_USERNAME/python-webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION --push .
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
