version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhub-G8QpL5:DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: arn:aws:secretsmanager:ap-south-1:339712721384:secret:dockerhub-G8QpL5:DOCKERHUB_PASSWORD

phases:
  install:
    commands:
      - echo "Installing Docker..."
      - apt-get update && apt-get install -y docker.io
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Building Docker image for game..."
      - cd game
      - docker build -t $DOCKERHUB_USERNAME/python-game:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker run --rm $DOCKERHUB_USERNAME/python-game:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - cd ../webapp
      - echo "Building Docker image for webapp..."
      - docker build -t $DOCKERHUB_USERNAME/python-webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  build:
    commands:
      - echo "Pushing Docker images to Docker Hub..."
      - docker push $DOCKERHUB_USERNAME/python-game:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $DOCKERHUB_USERNAME/python-webapp:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
